# Generated by Django 5.2.7 on 2025-10-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetails",
            name="course_full_name",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="coursedetails",
            name="course_name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
