# Generated by Django 5.2.7 on 2025-10-05 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0003_usercontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_payment_completed", models.BooleanField(default=False)),
                ("transaction_uuid", models.CharField(max_length=64, unique=True)),
                ("product_code", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="INITIATED",
                        max_length=16,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Khalti", "Khalti"),
                            ("e-Sewa", "e-Sewa"),
                            ("cash", "Cash"),
                        ],
                        default="e-Sewa",
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="admissionapp.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esewa_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
