# Generated by Django 5.2.7 on 2025-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0004_paymentdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="INITIATED",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentdetail",
            constraint=models.UniqueConstraint(
                fields=("application",), name="unique_payment_per_application"
            ),
        ),
    ]
