# Generated by Django 5.2.7 on 2025-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0005_alter_paymentdetail_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
