# Generated by Django 5.2.7 on 2025-10-06 11:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0006_application_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
