# Generated by Django 5.2.7 on 2025-10-08 12:16

import admissionapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0007_paymentdetail_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='bg_pic',
            field=models.ImageField(blank=True, help_text='Upload a background image for the course', null=True, upload_to=admissionapp.models.course_bg_upload_path, verbose_name='Background Picture'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_desc',
            field=models.TextField(blank=True, help_text='Overview, curriculum etc', verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_full_name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Course Full Name'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='course_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Course Name(short form)'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
